import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import LetterHead from "./components/LetterHead";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LetterHead />
        <NavBar />
        {children}</body>
    </html>
  );
}
